# CI for nelnet-ci dashboard

name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  deploy-dashboard:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    runs-on: self-hosted
    steps:
      - name: Deploy dashboard
        run: |
          cd /home/ben/src/nelnet-ci
          git fetch origin
          git reset --hard origin/master
          cd dashboard
          docker compose down
          docker compose up -d --build
